# Generated by Django 3.2.7 on 2021-09-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210902_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mews',
            new_name='news',
        ),
    ]
