# Generated by Django 3.2.7 on 2021-09-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
