# Generated by Django 3.2.7 on 2021-09-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
