# Generated by Django 3.2.7 on 2021-09-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
